### ISSUE TITLE
Getting PHP error on pfsense+ 23.01...

### ISSUE THREAD

**Issue by eapinero** [jullrich/dshieldpfsense#17]
I'm getting the following error after running ./dshieldpfsense.php:

PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /root/bin/dshieldpfsense.php:156
Stack trace:
#0 {main}
  thrown in /root/bin/dshieldpfsense.php on line 156

**Comment by ree4** [comment]
I can confirm @eapinero's report. Facing the same issue on my system, as well as the one reported [here](https://forum.netgate.com/post/1076021). In the thread, @jim-p explains the file needs re-worked to reflect the move to a newer PHP version. While another user provided feedback about their experience getting the file working.

Monitoring this to see if there is a patch.

[PHP_errors.log](https://github.com/jullrich/dshieldpfsense/files/11413294/PHP_errors.log)
![Selection_308](https://user-images.githubusercontent.com/14001007/236644462-f83f7712-2c22-416d-a61e-72d198c2215c.png)
![Selection_309](https://user-images.githubusercontent.com/14001007/236644479-304207a2-a274-4d94-ad78-36b3597dc42c.png)
![Selection_310](https://user-images.githubusercontent.com/14001007/236644513-c26dfd33-d1d0-44bb-9b06-bc77abd92254.png)

**Comment by masking-duck** [comment]
I'm also experiencing the same error message, same pfsense release.

**Comment by jullrich** [comment]
This has been resolved. Thanks for everybody's help in resolving this.

**Comment by gderf** [comment]
I upgraded to pfsense CE 2.7.0 today which broke the script as described in this issue. I replaced the script with the updated PFSense Client Version 0.000006 but it still throws an error. The line number reported (195) seems to be inconsistent with the original bug reporting.

I am pasting line 195 here, and the error below that.

`print "Log was rejected due to wrong interface or flags or because it is ICMP or the IP version is not 4 or the source is our own IP address: protocol {$flent['proto']} interface {$flent['interface']} flags {$flent['tcpflags']} version {$flent['version']} source ip {$flent['srcip']}\n";`

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /root/bin/dshield.php:195
Stack trace:
#0 {main}
  thrown in /root/bin/dshield.php on line 195
PHP ERROR: Type: 1, File: /root/bin/dshield.php, Line: 195, Message: Uncaught TypeError: Cannot access offset of type string on string in /root/bin/dshield.php:195
Stack trace:
#0 {main}
  thrown
